pub mod jwt;
pub mod jwt_blacklist;
pub mod middleware;
pub mod oauth;
pub mod password;
pub mod rate_limit;
pub mod roles;
pub mod saml;
pub mod session;
pub mod totp;

pub use jwt::JwtManager;
pub use jwt_blacklist::{blacklist_token, is_blacklisted};
pub use middleware::AuthLayer;
pub use oauth::{OAuthClient, OAuthConfig, OAuthProvider, OAuthUserInfo};
pub use password::{PasswordHasher, PasswordPolicy};
pub use rate_limit::LoginAttemptTracker;
pub use roles::{Capability, Role};
pub use saml::{SamlAssertion, SamlProvider, SamlSp};
pub use session::SessionManager;
pub use totp::{generate_qr_uri, generate_secret, verify_code as verify_totp};
